### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by Chandler-Kluser** [openXC7/toolchain-nix#12] opened 2023-12-20 03:15 UTC
Hello, Dear Friend @hansfbaier 😊

I have got this error by building the nix container:

```
$ sudo nix develop github:openxc7/toolchain-nix
warning: Ignoring setting 'auto-allocate-uids' because experimental feature 'auto-allocate-uids' is not enabled
warning: Ignoring setting 'impure-env' because experimental feature 'configurable-impure-env' is not enabled
error: builder for '/nix/store/mxs3ylimazpplc0qylq57i00qgagbbr3-nextpnr-xilinx-0.7.0.drv' failed with exit code 2;
       last 10 log lines:
       > [ 42%] Built target bbasm
       > /build/source/common/pybindings.cc: In function 'void nextpnr_xilinx::init_python(const char*, bool)':
       > /build/source/common/pybindings.cc:288:82: warning: 'boost::filesystem::path& boost::filesystem::path::normalize()' is deprecated: Use path::lexically_normal() instead [8;;https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wdeprecated-declarations-Wdeprecated-declarations8;;]
       >   288 |         boost::filesystem::path cwd = boost::filesystem::absolute("./").normalize();
       >       |                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
       > In file included from include/boost/filesystem.hpp:16,
       >                  from /build/source/common/pybindings.cc:29:
       > include/boost/filesystem/path.hpp:1434:14: note: declared here
       > make[1]: *** [CMakeFiles/Makefile2:112: CMakeFiles/nextpnr-xilinx.dir/all] Error 2
       > make: *** [Makefile:136: all] Error 2
       For full logs, run 'nix log /nix/store/mxs3ylimazpplc0qylq57i00qgagbbr3-nextpnr-xilinx-0.7.0.drv'.
error: 1 dependencies of derivation '/nix/store/zb1mi52n2dimwz5z914xarfxsakqhx8n-nix-shell-env.drv' failed to build
```

Do you know how to overcome this issue? Have you faced this before? Thanks in advance!!

**Comment by hansfbaier** [comment] 2023-12-20 03:19
Have not seen this before. Why do you need sudo here?

**Comment by hansfbaier** [comment] 2023-12-20 03:26
I just tried this command (without sudo) on Ubuntu and Arch, and both worked fine.

**Comment by hansfbaier** [comment] 2023-12-20 03:27
Closing this, as I can't reproduce. Feel free to reopen if you have instructions for that I can reproduce.

**Closed by hansfbaier** 2023-12-20 03:27 UTC

**Comment by Chandler-Kluser** [comment] 2023-12-20 03:30
I have installed `nix` using [Official Arch Linux Package](https://archlinux.org/packages/extra/x86_64/nix/) through pacman:

```
sudo pacman -S nix
```

Just like `docker`, I need to run containers/images with `sudo`:
![image](https://github.com/openXC7/toolchain-nix/assets/29960960/4417856d-27f4-4e47-ac27-5dbfb0cf0008)

**Comment by hansfbaier** [comment] 2023-12-20 04:15
@Chandler-Kluser The packaged Arch nix did not work for me properly. I uninstalled it and used the official nix installer 
like in this README
https://github.com/openXC7/toolchain-nix/

**Comment by Chandler-Kluser** [comment] 2023-12-20 14:13
> @Chandler-Kluser The packaged Arch nix did not work for me properly. I uninstalled it and used the official nix installer like in this README https://github.com/openXC7/toolchain-nix/

I know that, I prefer using the package manager because the installation process is reversible. I am not sure if running this script can be undone, too.

I will use it in a Virtual Machine with NixOS, instead, thanks in advance! 😊
